### ISSUE TITLE
Scratch Extension

### ISSUE THREAD

**Issue by kumar1250324** [IBM/taxinomitis#315]
below is my error message
lib.min.js:236699 vm Primitive rejected promise: DOMException: Failed to execute 'postMessage' on 'Worker': function Date() { [native code] } could not be cloned.
at http:/xxx/lib.min.js:267451:20
at new Promise ()
at CentralDispatch._remoteTransferCall (xxx/lib.min.js:267434:14)
at CentralDispatch.transferCall (http://xxx/lib.min.js:267373:45)
at CentralDispatch.call (http://xxx/lib.min.js:267341:32)
at serviceObject (http://xxx/lib.min.js:276775:35)
at blockInfo.func (http://xxx/lib.min.js:276795:22)
at execute (http://xxx/lib.min.js:270389:34)
at Sequencer.stepThread (http://xxx/lib.min.js:274348:11)
at Sequencer.stepThreads (http://xxx:lib.min.js:274254:18)

**Comment by dalelane** [comment]
@kumar1250324 Please can you provide a little context about what this is and what you'd like me to do with it?

When did this error occur? Where did it occur? What were you doing at the time? What problem did it cause? etc.

**Comment by kumar1250324** [comment]
@dalelane Hello.. i was trying to load the extensions  in scratch 3.
I was trying to do it in my local machine by using sheeptester scratch gui.(public/scratch3)
Can you please brief about how to run scratch3 with mlforskids blocks extensions in my local machine.

**Comment by dalelane** [comment]
Sorry, what you're trying to do isn't going to work - I haven't made the extension compatible with the sheeptester GUI.

**Comment by kumar1250324** [comment]
@dalelane Can u please tell the steps to integrate scratch 3 official with your tool MLforkids?

**Comment by dalelane** [comment]
I don't think that it's possible - there are too many modifications needed to enable it to work
