### ISSUE TITLE
Uncaught TypeError: loggerService.debug is not a function

### ISSUE THREAD

**Issue by nijisakai** [IBM/taxinomitis#338]
niji@L440:~/work/taxinomitis$ npm start

> ml-for-kids@0.0.1 start /home/niji/work/taxinomitis
> node dist/lib/app.js

chrome console:
```
jquery.min.js:2 jQuery.Deferred exception: loggerService.debug is not a function TypeError: loggerService.debug is not a function
    at confirmLocalStorage (http://45.76.19.205:3000/static/mlapp-1602817343127.min.js:570:27)
    at new authService (http://45.76.19.205:3000/static/mlapp-1602817343127.min.js:206:9)
    at Object.instantiate (http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:45:365)
    at Object.<anonymous> (http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:46:142)
    at Object.invoke (http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:45:264)
    at Object.$get (http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:42:378)
    at Object.invoke (http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:45:264)
    at http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:47:58
    at d (http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:44:197)
    at e (http://45.76.19.205:3000/static/bower_components/angular/angular.min.js:44:438) undefined
S.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: loggerService.debug is not a function
    at confirmLocalStorage (mlapp-1602817343127.min.js:570)
    at new authService (mlapp-1602817343127.min.js:206)
    at Object.instantiate (angular.js:5223)
    at Object.<anonymous> (angular.js:5059)
    at Object.invoke (angular.js:5208)
    at Object.$get (angular.js:5043)
    at Object.invoke (angular.js:5208)
    at angular.js:4997
    at d (angular.js:5151)
    at e (angular.js:5176)
```

Need help plesase.

**Comment by dalelane** [comment]
This is likely because the [required environment variables](https://github.com/IBM/taxinomitis/blob/master/DEVELOPMENT.md#step-4---set-up-your-environment-variables) were not set before building and running the app.
