### ISSUE TITLE
Unicode characters in project names

### ISSUE THREAD

**Issue by dalelane** [IBM/taxinomitis#58]
A few errors in production.... looks like someone was trying to create a project with a name made up of Unicode characters

```
2018-07-16T09:47:30.69+0100 [APP/PROC/WEB/2] ERR {"name":"ml-for-kids","hostname":"032dfbf0-71c7-4343-46d6-8b3a","pid":51,"level":50,"err":{"message":"Incorrect string value: '\\xEF\\xBC\\x9F' for column 'name' at row 1","name":"Error","stack":"Error: Incorrect string value: '\\xEF\\xBC\\x9F' for column 'name' at row 1\n    at PromisePoolConnection.PromiseConnection.execute (/home/vcap/app/node_modules/mysql2/promise.js:102:20)\n    at Object.storeProject (/home/vcap/app/dist/lib/db/store.js:100:47)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD"},"msg":"DB error","time":"2018-07-16T08:47:30.698Z","v":0}
```

**Comment by dalelane** [comment]
Presumably they were trying to call their project:  ï¼Ÿ

**Comment by dalelane** [comment]
I quickly tried creating a project with that name and it seemed to handle it fine. That's odd.

**Comment by dalelane** [comment]
There we go.... an emoji will do it

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/1444788/42752530-1f5f1144-88e6-11e8-9d80-ffe887399046.png">

`2018-07-16T10:50:25.95+0100 [APP/PROC/WEB/0] ERR {"name":"ml-for-kids","hostname":"e8961500-1d42-43d7-423e-2dfc","pid":57,"level":50,"err":{"message":"Incorrect string value: '\\xE2\\x9A\\xBD' for column 'name' at row 1","name":"Error","stack":"Error: Incorrect string value: '\\xE2\\x9A\\xBD' for column 'name' at row 1\n    at PromisePoolConnection.PromiseConnection.execute (/home/vcap/app/node_modules/mysql2/promise.js:102:20)\n    at Object.storeProject (/home/vcap/app/dist/lib/db/store.js:100:47)\n    at <anonymous>\n    at process._tickDomainCallback (internal/process/next_tick.js:228:7)","code":"ER_TRUNCATED_WRONG_VALUE_FOR_FIELD"},"msg":"Server error","time":"2018-07-16T09:50:25.953Z","v":0}`
